# Copyright (c) 2016-2020 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Dados Abertos de Tucano 
site_url: https://dadosabertostucano.org
site_author: Carlos André 
site_description: >-
  Aplicação para acesso e análise de dados abertos do município de Tucano, Bahia.

# Repository
repo_name: Dados Abertos Tucano
repo_url: https://github.com/dadosabertostucano/
edit_uri: ""

# Copyright
copyright: 2021 - Iniciativa de Inovação Cívica Dados Abertos de Tucano

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: pt
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: Teal
    accent: Teal
  font:
    text: Helvetica
    code: Roboto Mono
  icon:
    logo: logo
  favicon: assets/favicon.png

# Plugins
plugins:
  - macros
  - search
  - minify:
      minify_html: true

# Customization
extra:
  unit:
    price: 22.48
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dadosabertostucano
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/dadostucano

# Extensions
# Equations
extra_javascript:
 # - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
  - footnotes 
  - attr_list
  - def_list
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Sobre:
    - Home: sobre/index.md
    - Participe: sobre/participe.md
    - Fonte de dados: sobre/fonte-de-dados.md
    - Privacidade: sobre/privacidade.md
    - Acessibilidade: sobre/acessibilidade.md
    - Município de Tucano: sobre/municipio-tucano.md
  - Explore:
    - Dados: explore-dados/index.md
  - Dados Abertos Prefeitura:
    - Home: dados-prefeitura/index.md
    - Gestão 2021-2024: dados-prefeitura/gestao-secretarias.md
    - E-SIC: dados-prefeitura/e-sic.md 
    - Diário Oficial: dados-prefeitura/diario-oficial.md
    - Diárias: dados-prefeitura/diarias.md
    - Despesas: dados-prefeitura/despesas.md
    - Decretos: dados-prefeitura/decretos.md
    - Folha Pessoal: dados-prefeitura/folha-de-pessoal.md
    - Contratos: dados-prefeitura/contratos.md 
    - Licitações: dados-prefeitura/licitacoes.md
    - Editais: dados-prefeitura/editais.md
    - Leis: dados-prefeitura/leis.md
    - Relatório Fiscal: dados-prefeitura/relatorio-responsabilidade-fiscal.md
    - Estrutura: dados-prefeitura/estrutura-organizacional.md 
    - Convênios: dados-prefeitura/convenios.md
    - Receitas: dados-prefeitura/receitas.md
    - Extra Orçamentário: dados-prefeitura/extra-orcamentario.md
    - Repasse Financeiro: dados-prefeitura/repasse-financeiro.md
  - Dados Abertos Câmara de Vereadores:
    - Home: dados-camara-vereadores/index.md
    - Folha de Pessoal: dados-camara-vereadores/folha-de-pessoal.md
    - Vereadores: dados-camara-vereadores/vereadores.md
    - Despesas: dados-camara-vereadores/despesas.md
    - E-SIC: dados-camara-vereadores/e-sic.md
    - Contratos e Aditivos: dados-camara-vereadores/contratos-e-aditivos.md
    - Diário Oficial: dados-camara-vereadores/diario-oficial.md
    - Licitações: dados-camara-vereadores/licitacoes.md
    - Contas Públicas: dados-camara-vereadores/contas-publicas.md
    - Patrimônio Público: dados-camara-vereadores/patrimonio-publico.md
  - Dados Abertos COVID-19:
    - Home: dados-covid-19/index.md
  - Dados Abertos Vacinação contra COVID-19:
    - Home: dados-vacinacao-covid-19/index.md
  - Dados Abertos Auxílios Sociais:
    - Home: dados-auxilios-sociais/index.md
  - Dados Abertos Eleições:
    - Home: dados-eleicoes/index.md
  - Dados Abertos Educacionais:
    - Home: dados-educacionais/index.md
  - Dados Abertos de Saúde:
    - Home: dados-de-saude/index.md
  - Dados Abertos Ambientais:
    - Home: dados-ambientais/index.md
  - Dados Abertos Empresas:
    - Home: dados-empresas/index.md
  - Dados Abertos Empregos:
    - Home: dados-empregos/index.md
  - Análise de Dados:
    - Home: dados-analises/index.md
    - Análise Prefeitura: 
      - Análise sobre acesso à informação: dados-analises/25-03-2021-analise-prefeitura-acesso-a-informacao.md
    #- Análise Câmara: 
      #- Análise sobre Acesso à informação: dados-analises/20-03-2021-analise-camara-acesso-a-informacao.md
# Google Analytics
#google_analytics:
  #- !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  #- auto
